-- ============================================================
-- 0019 — Le quiz descend du serveur
-- ============================================================
--
-- CE QUE CETTE MIGRATION CORRIGE :
--
-- `DEMO_QUIZ` (lib/content/session-data.ts) était une constante GLOBALE,
-- utilisée sans aucune référence à `module_id` (session-view.tsx). Tout
-- module affichait donc les deux mêmes questions — un module créé depuis le
-- tableau de bord héritait du quiz du module 1.
--
-- Ce n'était pas une fonctionnalité manquante : l'application affichait
-- quelque chose de FAUX.
--
-- Le quiz rejoint donc les modules dans Supabase, avec le même mécanisme :
-- lecture publique du contenu publié, écriture réservée aux admins.

-- ------------------------------------------------------------
-- 1. Les questions
-- ------------------------------------------------------------
create table if not exists public.quiz_questions (
  id integer primary key generated by default as identity,
  module_id integer not null references public.modules (id) on delete cascade,
  -- Ordre d'affichage dans la séance.
  position integer not null default 1,
  -- Index de la bonne réponse dans le tableau `options` de la traduction.
  -- Il vit sur la QUESTION et non sur la traduction : la bonne réponse est
  -- la même quelle que soit la langue, seul son libellé change.
  correct_index integer not null default 0 check (correct_index >= 0),
  created_at timestamptz not null default now()
);

create index if not exists quiz_questions_module_idx
  on public.quiz_questions (module_id, position);

-- ------------------------------------------------------------
-- 2. Les traductions
-- ------------------------------------------------------------
create table if not exists public.quiz_question_translations (
  id uuid primary key default gen_random_uuid(),
  question_id integer not null references public.quiz_questions (id) on delete cascade,
  lang text not null,
  question text not null,
  options text[] not null default '{}',
  unique (question_id, lang)
);

-- ------------------------------------------------------------
-- 3. Politiques : mêmes règles que les modules
-- ------------------------------------------------------------
-- Lecture publique du seul contenu publié : l'app facilitateur est anonyme
-- au moment où elle télécharge le contenu (elle ne s'authentifie que pour
-- la synchro), exactement comme pour `modules`.
alter table public.quiz_questions enable row level security;
alter table public.quiz_question_translations enable row level security;

drop policy if exists "quiz: lecture du contenu publié" on public.quiz_questions;
create policy "quiz: lecture du contenu publié" on public.quiz_questions
  for select using (
    exists (
      select 1 from public.modules m
      where m.id = quiz_questions.module_id
        and m.status = 'published'
        and m.archived_at is null
    )
  );

drop policy if exists "quiz: lecture admin" on public.quiz_questions;
create policy "quiz: lecture admin" on public.quiz_questions
  for select using (public.is_admin());

drop policy if exists "quiz: écriture admin" on public.quiz_questions;
create policy "quiz: écriture admin" on public.quiz_questions
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "quiz_trad: lecture du contenu publié" on public.quiz_question_translations;
create policy "quiz_trad: lecture du contenu publié" on public.quiz_question_translations
  for select using (
    exists (
      select 1
      from public.quiz_questions q
      join public.modules m on m.id = q.module_id
      where q.id = quiz_question_translations.question_id
        and m.status = 'published'
        and m.archived_at is null
    )
  );

drop policy if exists "quiz_trad: lecture admin" on public.quiz_question_translations;
create policy "quiz_trad: lecture admin" on public.quiz_question_translations
  for select using (public.is_admin());

drop policy if exists "quiz_trad: écriture admin" on public.quiz_question_translations;
create policy "quiz_trad: écriture admin" on public.quiz_question_translations
  for all using (public.is_admin()) with check (public.is_admin());

-- ------------------------------------------------------------
-- 4. Contenu : deux questions par module
-- ------------------------------------------------------------
-- Les deux questions du module 1 reprennent l'ancien DEMO_QUIZ, pour ne rien
-- perdre. Les autres sont propres à chaque module — c'est précisément ce qui
-- n'existait pas avant.
--
-- Idempotent : rien n'est inséré si le module a déjà des questions.

do $$
declare
  v_module integer;
  v_qid integer;
  v_data jsonb := '[
    {"module": 1, "questions": [
      {"correct": 1,
       "fr": {"q": "Que faire quand un enfant fait une bêtise ?",
              "o": ["Le frapper pour qu''il retienne", "Comprendre et expliquer calmement", "L''ignorer complètement"]},
       "en": {"q": "What to do when a child misbehaves?",
              "o": ["Hit him so he remembers", "Understand and explain calmly", "Ignore him completely"]}},
      {"correct": 1,
       "fr": {"q": "Les 1000 premiers jours de l''enfant sont…",
              "o": ["Sans importance", "Décisifs pour son cerveau", "Réservés à la mère seule"]},
       "en": {"q": "A child''s first 1000 days are…",
              "o": ["Not important", "Decisive for the brain", "For the mother only"]}}
    ]},
    {"module": 2, "questions": [
      {"correct": 2,
       "fr": {"q": "À quel âge un enfant commence-t-il à apprendre ?",
              "o": ["À l''école primaire", "Vers 3 ans", "Dès la naissance"]},
       "en": {"q": "When does a child start learning?",
              "o": ["At primary school", "Around age 3", "From birth"]}},
      {"correct": 0,
       "fr": {"q": "Parler à un bébé qui ne répond pas encore, c''est…",
              "o": ["Utile : cela nourrit son cerveau", "Inutile, il ne comprend pas", "À éviter, cela le fatigue"]},
       "en": {"q": "Talking to a baby who cannot answer yet is…",
              "o": ["Useful: it feeds the brain", "Pointless, he does not understand", "Best avoided, it tires him"]}}
    ]},
    {"module": 3, "questions": [
      {"correct": 1,
       "fr": {"q": "Un enfant en colère a d''abord besoin…",
              "o": ["Qu''on le punisse", "Qu''on nomme ce qu''il ressent", "Qu''on le laisse seul"]},
       "en": {"q": "An angry child first needs…",
              "o": ["To be punished", "Someone to name what he feels", "To be left alone"]}},
      {"correct": 0,
       "fr": {"q": "Se mettre à la hauteur de l''enfant pour lui parler…",
              "o": ["L''aide à se sentir écouté", "Lui donne trop d''importance", "N''a aucun effet"]},
       "en": {"q": "Getting down to a child''s level to speak…",
              "o": ["Helps him feel heard", "Gives him too much importance", "Has no effect"]}}
    ]},
    {"module": 4, "questions": [
      {"correct": 2,
       "fr": {"q": "Que retient surtout un enfant qu''on frappe ?",
              "o": ["La règle qu''il a enfreinte", "Le respect de ses parents", "La peur, pas la leçon"]},
       "en": {"q": "What does a child who is hit mainly learn?",
              "o": ["The rule he broke", "Respect for his parents", "Fear, not the lesson"]}},
      {"correct": 1,
       "fr": {"q": "Des règles efficaces à la maison sont…",
              "o": ["Nombreuses et strictes", "Peu nombreuses et claires", "Différentes chaque jour"]},
       "en": {"q": "Effective rules at home are…",
              "o": ["Many and strict", "Few and clear", "Different every day"]}}
    ]},
    {"module": 5, "questions": [
      {"correct": 1,
       "fr": {"q": "Pour jouer avec son enfant, il faut…",
              "o": ["Acheter des jouets", "Ce qu''on a sous la main", "Attendre ses 3 ans"]},
       "en": {"q": "To play with your child you need…",
              "o": ["To buy toys", "Whatever is at hand", "To wait until age 3"]}},
      {"correct": 0,
       "fr": {"q": "Pendant le jeu, il vaut mieux…",
              "o": ["Laisser l''enfant mener", "Tout diriger soi-même", "Le laisser jouer seul"]},
       "en": {"q": "During play it is better to…",
              "o": ["Let the child lead", "Direct everything yourself", "Let him play alone"]}}
    ]},
    {"module": 6, "questions": [
      {"correct": 2,
       "fr": {"q": "Jusqu''à quel âge l''allaitement exclusif est-il recommandé ?",
              "o": ["2 mois", "4 mois", "6 mois"]},
       "en": {"q": "Exclusive breastfeeding is recommended until…",
              "o": ["2 months", "4 months", "6 months"]}},
      {"correct": 1,
       "fr": {"q": "La fenêtre des 1000 jours va…",
              "o": ["De 1 à 3 ans", "De la grossesse à 2 ans", "De 2 à 5 ans"]},
       "en": {"q": "The 1000-day window runs…",
              "o": ["From age 1 to 3", "From pregnancy to age 2", "From age 2 to 5"]}}
    ]},
    {"module": 7, "questions": [
      {"correct": 0,
       "fr": {"q": "Ce qui compte le plus chez un père, c''est…",
              "o": ["Sa présence au quotidien", "L''argent qu''il rapporte", "Son autorité"]},
       "en": {"q": "What matters most in a father is…",
              "o": ["His daily presence", "The money he brings", "His authority"]}},
      {"correct": 1,
       "fr": {"q": "Porter et consoler son bébé, pour un père…",
              "o": ["N''est pas son rôle", "Fait partie de son rôle", "Doit rester exceptionnel"]},
       "en": {"q": "For a father, holding and comforting his baby…",
              "o": ["Is not his role", "Is part of his role", "Should stay exceptional"]}}
    ]},
    {"module": 8, "questions": [
      {"correct": 2,
       "fr": {"q": "Quand un enfant subit des violences, il est…",
              "o": ["Un peu responsable", "Responsable s''il a désobéi", "Jamais responsable"]},
       "en": {"q": "When a child suffers violence, he is…",
              "o": ["Partly responsible", "Responsible if he disobeyed", "Never responsible"]}},
      {"correct": 0,
       "fr": {"q": "Face à une situation de danger, il faut…",
              "o": ["Signaler aux services compétents", "Attendre que ça passe", "Régler cela en famille"]},
       "en": {"q": "Faced with a dangerous situation, one should…",
              "o": ["Report to the proper services", "Wait for it to pass", "Handle it within the family"]}}
    ]}
  ]'::jsonb;
  v_mod jsonb;
  v_q jsonb;
  v_pos integer;
begin
  for v_mod in select * from jsonb_array_elements(v_data) loop
    v_module := (v_mod ->> 'module')::integer;

    -- Idempotence : on ne touche pas à un module qui a déjà des questions.
    if exists (select 1 from public.quiz_questions where module_id = v_module) then
      continue;
    end if;
    if not exists (select 1 from public.modules where id = v_module) then
      continue;
    end if;

    v_pos := 1;
    for v_q in select * from jsonb_array_elements(v_mod -> 'questions') loop
      insert into public.quiz_questions (module_id, position, correct_index)
      values (v_module, v_pos, (v_q ->> 'correct')::integer)
      returning id into v_qid;

      insert into public.quiz_question_translations (question_id, lang, question, options)
      values
        (v_qid, 'fr', v_q -> 'fr' ->> 'q',
         array(select jsonb_array_elements_text(v_q -> 'fr' -> 'o'))),
        (v_qid, 'en', v_q -> 'en' ->> 'q',
         array(select jsonb_array_elements_text(v_q -> 'en' -> 'o')));

      v_pos := v_pos + 1;
    end loop;
  end loop;
end $$;
