-- ============================================================
-- 0021 — Langues, régions et localités pilotables
-- ============================================================
--
-- CE QUE CETTE MIGRATION CORRIGE :
--
-- Les quatre langues étaient codées en dur à CINQ endroits : lang-pills.tsx,
-- content-matrix.tsx, actions.ts, et deux fois dans la page contenus.
-- Ajouter l'ewondo ou le bassa exigeait de modifier cinq fichiers — en
-- contradiction directe avec la promesse affichée sur la landing :
-- « ajouter une langue = remplir une case, sans refonte ».
--
-- Le mécanisme fonctionnait pour les MÉDIAS d'une langue existante, pas pour
-- créer la langue elle-même.
--
-- Même problème pour les régions (3 en dur dans login/page.tsx) et les
-- localités (4 villages de l'Extrême-Nord dans session-data.ts) : un
-- facilitateur d'une autre région ne trouvait pas la sienne.

-- ------------------------------------------------------------
-- 1. Langues
-- ------------------------------------------------------------
create table if not exists public.languages (
  -- Code court utilisé partout dans le contenu (module_translations.lang).
  code text primary key,
  -- Libellé long, pour l'accessibilité (title, aria-label).
  label text not null,
  -- Libellé court affiché sur les pastilles du facilitateur.
  short_label text not null,
  -- Ordre d'affichage.
  position integer not null default 99,
  -- Une langue désactivée disparaît de l'interface sans perdre son contenu :
  -- c'est l'équivalent de l'archivage des modules.
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.languages (code, label, short_label, position) values
  ('fr',   'Français',          'FR',       1),
  ('en',   'Anglais',           'EN',       2),
  ('sign', 'Langue des signes', 'LSF',      3),
  ('ff',   'Fulfulde',          'Fulfulde', 4)
on conflict (code) do nothing;

-- ------------------------------------------------------------
-- 2. Régions
-- ------------------------------------------------------------
create table if not exists public.regions (
  id integer primary key generated by default as identity,
  name text not null unique,
  position integer not null default 99,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Les trois régions du déploiement pilote, plus celles déjà présentes dans
-- les séances déjà synchronisées (sinon un facilitateur existant ne
-- retrouverait pas la sienne).
insert into public.regions (name, position) values
  ('Extrême-Nord', 1),
  ('Adamaoua',     2),
  ('Nord-Ouest',   3)
on conflict (name) do nothing;

insert into public.regions (name)
select distinct region from public.sessions
where region is not null and region <> ''
on conflict (name) do nothing;

-- ------------------------------------------------------------
-- 3. Localités
-- ------------------------------------------------------------
create table if not exists public.localities (
  id integer primary key generated by default as identity,
  region_id integer not null references public.regions (id) on delete cascade,
  name text not null,
  position integer not null default 99,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (region_id, name)
);

-- Les localités du pilote, rattachées à l'Extrême-Nord.
insert into public.localities (region_id, name, position)
select r.id, v.name, v.pos
from public.regions r
cross join (values ('Maroua', 1), ('Mokolo', 2), ('Kousséri', 3), ('Mora', 4))
  as v(name, pos)
where r.name = 'Extrême-Nord'
on conflict (region_id, name) do nothing;

-- Les localités déjà utilisées dans des séances réelles : sans elles, un
-- facilitateur ne retrouverait pas le lieu où il a déjà animé.
insert into public.localities (region_id, name)
select distinct r.id, s.locality
from public.sessions s
join public.regions r on r.name = s.region
where s.locality is not null and s.locality <> ''
on conflict (region_id, name) do nothing;

-- ------------------------------------------------------------
-- 4. Politiques : référentiel lisible par tous, écrit par les admins
-- ------------------------------------------------------------
-- Lecture ANONYME et non « publié uniquement » comme pour les modules :
-- l'app facilitateur a besoin des langues et des régions dès l'écran de
-- CONNEXION, avant toute authentification. Ces tables ne contiennent aucune
-- donnée personnelle — seulement des noms de langues et de lieux.

alter table public.languages enable row level security;
alter table public.regions enable row level security;
alter table public.localities enable row level security;

drop policy if exists "languages: lecture publique" on public.languages;
create policy "languages: lecture publique" on public.languages
  for select using (true);

drop policy if exists "languages: écriture admin" on public.languages;
create policy "languages: écriture admin" on public.languages
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "regions: lecture publique" on public.regions;
create policy "regions: lecture publique" on public.regions
  for select using (true);

drop policy if exists "regions: écriture admin" on public.regions;
create policy "regions: écriture admin" on public.regions
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "localities: lecture publique" on public.localities;
create policy "localities: lecture publique" on public.localities
  for select using (true);

drop policy if exists "localities: écriture admin" on public.localities;
create policy "localities: écriture admin" on public.localities
  for all using (public.is_admin()) with check (public.is_admin());
